SELECT *                                                                00010000
FROM SYSIBM.SYSTABLES                                                   00020005
WHERE OWNER='IBMUSER'                                                   00021003
;                                                                       00030000
SELECT *                                                                00031006
FROM SYSIBM.SYSCOLUMNS                                                  00032006
WHERE TBNAME='COPA_MUNDO'                                               00033009
;                                                                       00034006
                                                                        00040006
